backend/models/BookForm.php
<?php
/**
 * Файл для создания/редактирования книги, загрузки обложки книги.
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 8:15 PM
 */

namespace backend\models;

use avega\F;
use common\models\Book;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * Class BookForm
 * @package backend\models
 * @property $cover string|UploadedFile
 * @property $title string
 * @property $description string
 * @property $cutFiles boolean
 */
class BookForm extends Book
{
    const SCENARIO_EDIT = 'edit';
    const SCENARIO_CREATE = 'create';
    /**
     * Для загрузки обложки.
     */
    const SCENARIO_COVER = 'cover';

    /**
     * Ширина миниатюры.
     */
    const THUMBNAIL_WIDTH = 120;
    /**
     * Высота миниатюры.
     */
    const THUMBNAIL_HEIGHT = 120;

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'title' => 'Название',
            'cover' => 'Обложка',
            'description' => 'Описание',
            'cutFiles' => 'Разрезать каждый новый файл пополам'
        ];
    }

    /**
     * @return array
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_COVER => ['cover'],
            self::SCENARIO_EDIT => ['cover', 'title', 'description', 'cutFiles'],
            self::SCENARIO_CREATE => ['cover', 'title', 'description', 'cutFiles']
        ];
    }

    /**
     * Перед сохранением книги, удяляем её старую обложку, если загрузили новую.
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->cover != $this->getOldAttribute('cover')) {
            $this->deleteCurrentCover();
        }

        return parent::beforeSave($insert);
    }

    /**
     * Сохраняет обложку книги.
     * @return bool
     */
    public function uploadCover()
    {
        $fileName = time() + mt_rand(-1000, 1000) . '_' . $this->cover->name;
        // имя для миниатюры
        $thumbnailName = self::THUMBNAIL_WIDTH . 'x' . self::THUMBNAIL_HEIGHT . '_' . $fileName;

        $filePath = \Yii::getAlias(\Yii::$app->params['coverPath'] . $fileName);
        $thumbnailPath = \Yii::getAlias(\Yii::$app->params['coverPath'] . $thumbnailName);

        // пытаемся сразу сохранить обложку,
        // сделать из неё миниатюру и тоже сохранить
        $save = $this->cover->saveAs($filePath) &&
            Image::thumbnail($filePath, self::THUMBNAIL_WIDTH, self::THUMBNAIL_HEIGHT)->save($thumbnailPath);

        return $save ? $fileName : false;
    }

    /**
     * Проверяет, существует ли файл обложки.
     * @param $attribute
     */
    public function checkCover($attribute)
    {
        if (self::getScenario() !== self::SCENARIO_COVER) {
            if (!is_file(\Yii::getAlias(\Yii::$app->params['coverPath'] . $this->cover))) {
                $this->addError($attribute, 'Файл обложки не существует.');
            }
        }
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
            [
                ['title', 'cover', 'description', 'cutFiles'],
                'required',
                'on' => [self::SCENARIO_EDIT, self::SCENARIO_CREATE]
            ],
            ['cover', 'checkCover'],
            ['cover', 'safe', 'on' => self::SCENARIO_COVER],
            [
                ['cover'],
                'file',
                'extensions' => 'png,jpg,jpeg',
                'skipOnEmpty' => true,
                'checkExtensionByMimeType' => false,
                'on' => self::SCENARIO_COVER
            ]
        ];
    }
}

common/models/Book.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 8:14 PM
 */

namespace common\models;


use backend\models\BookForm;
use yii\db\ActiveRecord;

/**
 * Class Book
 * @package common\models
 * @property $id integer
 * @property $title string
 * @property $cover string
 * @property $description string
 * @property $cutFiles boolean
 */
class Book extends ActiveRecord
{
    public static function tableName()
    {
        return 'book';
    }

    /**
     * Функция для with().
     * @return \yii\db\ActiveQuery
     */
    public function getSections()
    {
        return $this->hasMany(Section::className(), ['bookId' => 'id']);
    }

    /**
     * Удаляет книгу, главы в ней, изображения в каждой главе.
     * @param $id
     * @return bool
     */
    public static function remove($id)
    {
        $book = self::findOne($id);

        $sectionTableName = Section::tableName();
        $bookTableName = self::tableName();
        $imageTableName = Image::tableName();

        $images = self::find()
            ->select(["{$imageTableName}.file", "{$imageTableName}.id"])
            ->innerJoin($sectionTableName, "{$sectionTableName}.bookId = {$bookTableName}.id")
            ->innerJoin($imageTableName, "{$imageTableName}.sectionId = {$sectionTableName}.id")
            ->where(["{$bookTableName}.id" => $id])
            ->asArray()
            ->all();

        foreach ($images as $image) {
            unlink(\Yii::getAlias(\Yii::$app->params['paperPath'] . $image['file']));
        }

        unlink(\Yii::getAlias(\Yii::$app->params['coverPath'] . $book->cover));

        // получаем массив id изображений чтобы удалить их все разом из бд
        $imagesId = array_map(function ($image) {
            return $image['id'];
        }, $images);

        // удаляет все изображения книги
        Image::deleteAll(['id' => $imagesId]);
        Section::deleteAll(['bookId' => $id]);

        // если кол-во затронутых строк == 1, тогда удаление прошло успешно
        return (bool)$book->delete();
    }

    /**
     * Удаляет существующую обложку.
     */
    protected function deleteCurrentCover() {
        if (!empty($this->getOldAttribute('cover'))) {
            $thumbnailPrefix = BookForm::THUMBNAIL_WIDTH . 'x' . BookForm::THUMBNAIL_HEIGHT . '_';

            unlink(\Yii::getAlias(\Yii::$app->params['thumbnailPath'] . $this->getOldAttribute('cover')));
            unlink(\Yii::getAlias(\Yii::$app->params['thumbnailPath'] . $thumbnailPrefix . $this->getOldAttribute('cover')));
        }
    }
}

backend/controllers/BooksController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 4:33 PM
 */

namespace backend\controllers;


use avega\F;
use backend\models\BookForm;
use common\models\Book;
use common\models\Section;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

class BooksController extends Controller
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    /**
     * Страница с книгами.
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'books' => Book::find()->orderBy('id DESC')->asArray()->all()
        ]);
    }

    /**
     * Страница редактировании книги.
     */
    public function actionEdit($id)
    {
        $book = Book::findOne($id);

        if ($book !== null) {
            return $this->render('edit', ['book' => $book]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Страница создания новой книги.
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Загрузка обложки (ajax).
     */
    public function actionUploadCover()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = [
            'status' => 0,
            'messages' => []
        ];

        $model = new BookForm(['scenario' => BookForm::SCENARIO_COVER]);
        $model->setAttribute('cover', UploadedFile::getInstanceByName('cover'));

        if ($model->validate()) {
            $uploadCover = $model->uploadCover();

            if ($uploadCover) {
                $response['status'] = 1;
                $response['messages'] = [
                    'Обложка загружена успешно.',
                    'Обложка будет обновлена после сохранения.'
                ];
                $response['fileName'] = $uploadCover;
            }
        } elseif ($model->hasErrors()) {
            $response['messages'] = $model->errors;
        } else {
            throw new BadRequestHttpException;
        }

        return $response;
    }

    /**
     * Обновляет книгу по id или создает новую, если id не указан (ajax).
     */
    public function actionSave($id = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = [
            'status' => 0,
            'messages' => []
        ];

        if ($id !== null) {
            $model = BookForm::findOne($id);
            $model->setScenario(BookForm::SCENARIO_EDIT);
        } else {
            $model = new BookForm(['scenario' => BookForm::SCENARIO_CREATE]);
        }

        if ($model->load(\Yii::$app->request->post(), 'form') && $model->save()) {
            $response['status'] = 1;
            $response['messages'] = 'Книга была успешно обновлена.';
            if ($id === null) {
                $response['messages'] = 'Книга «' . $model->title . '» была успешно создана.';
            }
        } elseif ($model->hasErrors()) {
            $response['messages'] = $model->errors;
        } else {
            throw new BadRequestHttpException;
        }

        return $response;
    }

    /**
     * Страница всех глав книги с id $id.
     */
    public function actionSections($id)
    {
        $book = Book::find()->select([
            'id',
            'title'
        ])->where(['id' => $id])->with('sections')->one();

        if ($book !== null) {
            return $this->render('sections', ['book' => $book]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Удаляет книгу (ajax).
     */
    public function actionDelete($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = ['status' => 0];

        if (Book::find()->where(['id' => $id])->exists()) {
            if (Book::remove($id)) {
                $response['status'] = 1;
                $response['messages'] = 'Книга была успешно удалена.';
            } else {
                $response['messages'] = 'Ошибка удаления книги.';
            }
        } else {
            throw new NotFoundHttpException;
        }

        return $response;
    }
}

backend/controllers/ImageController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 8/1/2016
 * Time: 12:59 PM
 */

namespace backend\controllers;

use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class ImageController extends Controller
{
    /**
     *
     */
    public function actionGetImage($fileName)
    {
        $imagePath = \Yii::getAlias(\Yii::$app->params['paperPath'] . $fileName);

        if (file_exists($imagePath)) {
            $response = \Yii::$app->getResponse();
            $response->headers->set('Content-Type', 'image/jpeg');
            $response->format = Response::FORMAT_RAW;

            if (!is_resource($response->stream = fopen($imagePath, 'r'))) {
                throw new ForbiddenHttpException;
            }

            return $response->send();
        } else {
            throw new NotFoundHttpException;
        }
    }
}

frontend/controllers/BooksController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/30/2016
 * Time: 11:40 PM
 */

namespace frontend\controllers;


use avega\F;
use common\models\Book;
use common\models\Image;
use common\models\Section;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BooksController extends Controller
{
    /**
     * Страница с книгами.
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'books' => Book::find()
                ->orderBy('id DESC')
                ->asArray()
                ->all()
        ]);
    }

    /**
     * Страница всех глав книги.
     */
    public function actionView($id)
    {
        $book = Book::findOne($id);

        if ($book !== null) {
            return $this->render('view', [
                'sections' => Section::findAll(['bookId' => $id]),
                'book' => $book
            ]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Страница просмотра изображений главы.
     */
    public function actionSection($id, $imageId = null)
    {
        $section = Section::findOne($id);

        if ($section !== null) {
            $book = Section::findBookBySectionId($id);

            return $this->render('images',
                [
                    'nextSection' => $section->getNextSection(),
                    'prevSection' => $section->getPrevSection(),
                    'book' => $book,
                    'section' => $section,
                    'images' => Image::find()
                        ->where(['sectionId' => $id])
                        ->select('id')
                        ->asArray()
                        ->all(),
                    'imageId' => $imageId
                ]);
        } else {
            throw new NotFoundHttpException;
        }
    }
}

frontend/controllers/ImageController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 8/1/2016
 * Time: 12:59 PM
 */

namespace frontend\controllers;


use frontend\components\filters\AjaxAccess;
use common\models\Image;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class ImageController extends Controller
{
    public function behaviors()
    {
        return [
            'verb' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'get-image' => ['post'],
                    'abracadabra' => ['put']
                ]
            ],
            'ajax' => [
                'class' => AjaxAccess::className(),
                'only' => ['get-image', 'abracadabra']
            ]
        ];
    }

    /**
     * Отдает изображение по id.
     */
    public function actionGetImage($id)
    {
        $image = Image::findOne($id);

        $abracadabra = \Yii::$app->request->post('abracadabra');

        if ($image !== null && $this->checkAbracadabra($abracadabra)) {
            $imagePath = \Yii::getAlias(\Yii::$app->params['paperPath'] . $image->file);
            $type = pathinfo($imagePath, PATHINFO_EXTENSION);
            $image = file_get_contents($imagePath);
//            $response = \Yii::$app->getResponse();
//            $response->headers->set('Content-Type', 'image/jpeg');
//            $response->format = Response::FORMAT_RAW;
//
//            if (!is_resource($response->stream = fopen($imagePath, 'r'))) {
//                throw new ForbiddenHttpException;
//            }
//
//            return $response->send();
            return 'data:image/' . $type . ';base64,' . base64_encode($image);
        }

        throw new NotFoundHttpException;
    }

    /**
     * Возвращает ключ для доступа к изображениям.
     */
    public function actionAbracadabra()
    {
        \Yii::$app->response->format = Response::FORMAT_RAW;
        return $this->generateAbracadabra();
    }

    /**
     * Верификация ключа.
     */
    private function checkAbracadabra($key)
    {
        return \Yii::$app->session->getFlash('abracadabra') === $key;
    }

    /**
     * Генерация ключа.
     */
    private function generateAbracadabra()
    {
        $key = \Yii::$app->security->generateRandomString();
        \Yii::$app->session->setFlash('abracadabra', $key);

        return $key;
    }
}

frontend/views/books/images.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 8/1/2016
 * Time: 1:00 PM
 * @var $images array. массив id изображений
 * @var $book \common\models\Book
 * @var $section \common\models\Section
 * @var $imageId integer
 * @var $nextSection \common\models\Section
 * @var $prevSection \common\models\Section
 */
?>
<div class="content">
    <div class="image-view">
        <div class="row section-navigation">
            <div class="col-xs-4">
                <a class="prev-section"
                   href="<?= $prevSection === null ? '#' : \yii\helpers\Url::to(['/books/section/' . $prevSection->id]) ?>" <?= $prevSection === null ? 'disabled' : '' ?>>
                    Глава
                </a>
            </div>
            <div class="col-xs-4">
                <a href="<?= \yii\helpers\Url::to(['/books/view/' . $book['id']]) ?>" class="to-all-sections">Оглавление</a>
            </div>
            <div class="col-xs-4">
                <a class="next-section"
                   href="<?= $nextSection === null ? '#' : \yii\helpers\Url::to(['/books/section/' . $nextSection->id]) ?>" <?= $nextSection === null ? 'disabled' : '' ?>>
                    Глава
                </a>
            </div>
        </div>
        <div class="row">
            <?php if (count($images) > 0): ?>
                <div id="image">
                    <a href="#" class="left">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                    <a href="#" class="right">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </div>
            <?php else: ?>
                <h3>В данной главе еще нет страниц.</h3>
            <?php endif ?>
        </div>
    </div>
</div>
<script>
    <?php if (count($images) > 0): ?>
    /**
     * Массив id изображений.
     */
    var ids = <?= json_encode($images) ?>;

    var Abracadabra = {
        /**
         * Возвращает токен.
         * @return {string}
         */
        get: function () {
            return $.ajax({
                url: '<?= \yii\helpers\Url::to(['/image/abracadabra']) ?>',
                type: 'PUT',
                async: false,
                data: {_csrf: '<?= Yii::$app->request->getCsrfToken() ?>'}
            }).responseText;
        }
    };

    var Image = {
        selectors: {
            image: '#image',
            left: '.left',
            right: '.right'
        },

        /**
         * id в бд первого изображения чтобы понять, что влево нельзя уже листать.
         */
        firstImageId: <?= $images[0]['id'] !== null ? $images[0]['id'] : 0 ?>,
        /**
         * id в бд последнего изображения чтобы понять, что вправо нельзя уже листать.
         */
        lastImageId: <?= $images[count($images) - 1]['id'] !== null ? $images[count($images) - 1]['id'] : 0 ?>,
        /**
         * Указатель на индекс в массиве изображений. Изначально 0, т.к. при заходе на страницу показывается первое изображение главы.
         */
        imagePointer: <?= 0 ?>,

        /**
         * Запрос на загрузку изображения по id, если указан.
         * @returns {boolean}
         */
        loadImage: function (id) {

            if (id === false) {
                id = ids[this.imagePointer].id;
            }

            var _this = this;

            $.ajax({
                url: '<?= \yii\helpers\Url::to(['/image/get-image']) ?>/' + id,
                type: 'POST',
                data: {_csrf: '<?= Yii::$app->request->getCsrfToken() ?>', abracadabra: Abracadabra.get()},
                success: function (response) {
                    _this.afterLoad(response, id);
                },
                error: function () {
                    alert('Ошибка загрузки изображения');
                }
            });
        },
        /**
         * После ajax запроса в фк-цию передается base64 код изображения.
         * @param id
         * @param response
         */
        afterLoad: function (response, id) {
            window.history.pushState({id: id}, 'Изображение №' + id, '<?= \yii\helpers\Url::to(['/books/section/' . $section->id]) ?>' + '/' + id);
            $(this.selectors.image).css({'background': 'url(' + response + ' )'});
        },
        /**
         * Листаем вправо.
         */
        incPointer: function () {
            this.imagePointer++;
        },
        /**
         * Листаем влево.
         */
        decPointer: function () {
            this.imagePointer--;
        }
    };

    /**
     * Клик по кнопке "предыдущее изображени"
     */
    $(Image.selectors.left).click(function () {
        // проверка, существует ли предыдущее изображение
        if (typeof ids[Image.imagePointer - 1] !== typeof undefined) {
            Image.decPointer();
            Image.loadImage(false);
        }
        return false;
    });

    /**
     * Клик по кнопке "следующее изображение"
     */
    $(Image.selectors.right).click(function () {
        // проверка, существует ли следующее изображение
        if (typeof ids[Image.imagePointer + 1] !== typeof undefined) {
            Image.incPointer();
            Image.loadImage(false);
        }
        return false;
    });

    $(function () {
        console.log(window.location.href);
        // если юзверь перешел на конкретное изображение
        // тогда проверяем, есть ли оно в массиве изображений
        // если да, вставляем id изображения, иначе false
        Image.loadImage(<?= $imageId !== null ? (array_search($imageId, array_column($images, 'id')) ? $imageId : 'false') : 'false' ?>);
    });
    <?php endif ?>
</script>

frontend/views/books/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/30/2016
 * Time: 11:52 PM
 * @var $books array
 */
$thumbnailWidth = \backend\models\ImagesForm::THUMBNAIL_WIDTH;
$thumbnailHeight = \backend\models\ImagesForm::THUMBNAIL_HEIGHT;
$thumbnailPrefix = $thumbnailWidth . 'x' . $thumbnailHeight . '_';
\backend\assets\LightBox2Asset::register($this);
?>
<div class="content">
    <div class="container">
        <div class="book-list">
            <?php foreach ($books as $book): ?>
                <div class="book-container">
                    <div class="cover-container">
                        <a data-lightbox="thumbnails" href="<?= Yii::$app->params['coverUrl'] . $book['cover'] ?>">
                            <img
                                src="<?= Yii::getAlias(Yii::$app->params['coverUrl'] . $thumbnailPrefix . $book['cover']) ?>"
                                alt="Обложка">
                        </a>
                    </div>
                    <div class="info-container">
                        <a href="<?= \yii\helpers\Url::to(['/books/view/' . $book['id']]) ?>"><?= $book['title'] ?></a>
                        <p><?= $book['description'] ?></p>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>

frontend/views/books/view.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 8/1/2016
 * Time: 10:47 AM
 * @var $sections
 * @var $book
 */
?>
<div class="content">
    <div class="container">
        <div class="section-book-name">
            <a href="<?= \yii\helpers\Url::to(['/books']) ?>">Книги</a> &raquo; <?= $book->title ?>
        </div>
        <?php if (count($sections) > 0): ?>
            <?php foreach ($sections as $section): ?>
                <div class="section-container">
                    <a href="<?= \yii\helpers\Url::to(['/books/section/' . $section['id']]) ?>"><?= $section->name ?></a>
                </div>
            <?php endforeach ?>
        <?php else: ?>
            <h4>В данной книге еще нет глав.</h4>
        <?php endif ?>
    </div>
</div>