backend/models/BookForm.php
<?php
/**
 * Файл для создания/редактирования книги, загрузки обложки книги.
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 8:15 PM
 */

namespace backend\models;

use avega\F;
use common\models\Book;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * Class BookForm
 * @package backend\models
 * @property $cover string|UploadedFile
 * @property $title string
 * @property $description string
 * @property $cutFiles boolean
 */
class BookForm extends Book
{
    const SCENARIO_EDIT = 'edit';
    const SCENARIO_CREATE = 'create';
    /**
     * Для загрузки обложки.
     */
    const SCENARIO_COVER = 'cover';

    /**
     * Ширина миниатюры.
     */
    const THUMBNAIL_WIDTH = 120;
    /**
     * Высота миниатюры.
     */
    const THUMBNAIL_HEIGHT = 120;

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'title' => 'Название',
            'cover' => 'Обложка',
            'description' => 'Описание',
            'cutFiles' => 'Разрезать каждый новый файл пополам'
        ];
    }

    /**
     * @return array
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_COVER => ['cover'],
            self::SCENARIO_EDIT => ['cover', 'title', 'description', 'cutFiles'],
            self::SCENARIO_CREATE => ['cover', 'title', 'description', 'cutFiles']
        ];
    }

    /**
     * Перед сохранением книги, удяляем её старую обложку, если загрузили новую.
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->cover != $this->getOldAttribute('cover')) {
            $this->deleteCurrentCover();
        }

        return parent::beforeSave($insert);
    }

    /**
     * Сохраняет обложку книги.
     * @return bool
     */
    public function uploadCover()
    {
        $fileName = time() + mt_rand(-1000, 1000) . '_' . $this->cover->name;
        // имя для миниатюры
        $thumbnailName = self::THUMBNAIL_WIDTH . 'x' . self::THUMBNAIL_HEIGHT . '_' . $fileName;

        $filePath = \Yii::getAlias(\Yii::$app->params['coverPath'] . $fileName);
        $thumbnailPath = \Yii::getAlias(\Yii::$app->params['coverPath'] . $thumbnailName);

        // пытаемся сразу сохранить обложку,
        // сделать из неё миниатюру и тоже сохранить
        $save = $this->cover->saveAs($filePath) &&
            Image::thumbnail($filePath, self::THUMBNAIL_WIDTH, self::THUMBNAIL_HEIGHT)->save($thumbnailPath);

        return $save ? $fileName : false;
    }

    /**
     * Проверяет, существует ли файл обложки.
     * @param $attribute
     */
    public function checkCover($attribute)
    {
        if (self::getScenario() !== self::SCENARIO_COVER) {
            if (!is_file(\Yii::getAlias(\Yii::$app->params['coverPath'] . $this->cover))) {
                $this->addError($attribute, 'Файл обложки не существует.');
            }
        }
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
            [
                ['title', 'cover', 'description', 'cutFiles'],
                'required',
                'on' => [self::SCENARIO_EDIT, self::SCENARIO_CREATE]
            ],
            ['cover', 'checkCover'],
            ['cover', 'safe', 'on' => self::SCENARIO_COVER],
            [
                ['cover'],
                'file',
                'extensions' => 'png,jpg,jpeg',
                'skipOnEmpty' => true,
                'checkExtensionByMimeType' => false,
                'on' => self::SCENARIO_COVER
            ]
        ];
    }
}

common/models/Book.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 8:14 PM
 */

namespace common\models;


use backend\models\BookForm;
use yii\db\ActiveRecord;

/**
 * Class Book
 * @package common\models
 * @property $id integer
 * @property $title string
 * @property $cover string
 * @property $description string
 * @property $cutFiles boolean
 */
class Book extends ActiveRecord
{
    public static function tableName()
    {
        return 'book';
    }

    /**
     * Функция для with().
     * @return \yii\db\ActiveQuery
     */
    public function getSections()
    {
        return $this->hasMany(Section::className(), ['bookId' => 'id']);
    }

    /**
     * Удаляет книгу, главы в ней, изображения в каждой главе.
     * @param $id
     * @return bool
     */
    public static function remove($id)
    {
        $book = self::findOne($id);

        $sectionTableName = Section::tableName();
        $bookTableName = self::tableName();
        $imageTableName = Image::tableName();

        $images = self::find()
            ->select(["{$imageTableName}.file", "{$imageTableName}.id"])
            ->innerJoin($sectionTableName, "{$sectionTableName}.bookId = {$bookTableName}.id")
            ->innerJoin($imageTableName, "{$imageTableName}.sectionId = {$sectionTableName}.id")
            ->where(["{$bookTableName}.id" => $id])
            ->asArray()
            ->all();

        foreach ($images as $image) {
            unlink(\Yii::getAlias(\Yii::$app->params['paperPath'] . $image['file']));
        }

        unlink(\Yii::getAlias(\Yii::$app->params['coverPath'] . $book->cover));

        // получаем массив id изображений чтобы удалить их все разом из бд
        $imagesId = array_map(function ($image) {
            return $image['id'];
        }, $images);

        // удаляет все изображения книги
        Image::deleteAll(['id' => $imagesId]);
        Section::deleteAll(['bookId' => $id]);

        // если кол-во затронутых строк == 1, тогда удаление прошло успешно
        return (bool)$book->delete();
    }

    /**
     * Удаляет существующую обложку.
     */
    protected function deleteCurrentCover() {
        if (!empty($this->getOldAttribute('cover'))) {
            $thumbnailPrefix = BookForm::THUMBNAIL_WIDTH . 'x' . BookForm::THUMBNAIL_HEIGHT . '_';

            unlink(\Yii::getAlias(\Yii::$app->params['thumbnailPath'] . $this->getOldAttribute('cover')));
            unlink(\Yii::getAlias(\Yii::$app->params['thumbnailPath'] . $thumbnailPrefix . $this->getOldAttribute('cover')));
        }
    }
}

backend/controllers/BooksController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 4:33 PM
 */

namespace backend\controllers;


use avega\F;
use backend\models\BookForm;
use common\models\Book;
use common\models\Section;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

class BooksController extends Controller
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    /**
     * Страница с книгами.
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'books' => Book::find()->orderBy('id DESC')->asArray()->all()
        ]);
    }

    /**
     * Страница редактировании книги.
     */
    public function actionEdit($id)
    {
        $book = Book::findOne($id);

        if ($book !== null) {
            return $this->render('edit', ['book' => $book]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Страница создания новой книги.
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Загрузка обложки (ajax).
     */
    public function actionUploadCover()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = [
            'status' => 0,
            'messages' => []
        ];

        $model = new BookForm(['scenario' => BookForm::SCENARIO_COVER]);
        $model->setAttribute('cover', UploadedFile::getInstanceByName('cover'));

        if ($model->validate()) {
            $uploadCover = $model->uploadCover();

            if ($uploadCover) {
                $response['status'] = 1;
                $response['messages'] = [
                    'Обложка загружена успешно.',
                    'Обложка будет обновлена после сохранения.'
                ];
                $response['fileName'] = $uploadCover;
            }
        } elseif ($model->hasErrors()) {
            $response['messages'] = $model->errors;
        } else {
            throw new BadRequestHttpException;
        }

        return $response;
    }

    /**
     * Обновляет книгу по id или создает новую, если id не указан (ajax).
     */
    public function actionSave($id = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = [
            'status' => 0,
            'messages' => []
        ];

        if ($id !== null) {
            $model = BookForm::findOne($id);
            $model->setScenario(BookForm::SCENARIO_EDIT);
        } else {
            $model = new BookForm(['scenario' => BookForm::SCENARIO_CREATE]);
        }

        if ($model->load(\Yii::$app->request->post(), 'form') && $model->save()) {
            $response['status'] = 1;
            $response['messages'] = 'Книга была успешно обновлена.';
            if ($id === null) {
                $response['messages'] = 'Книга «' . $model->title . '» была успешно создана.';
            }
        } elseif ($model->hasErrors()) {
            $response['messages'] = $model->errors;
        } else {
            throw new BadRequestHttpException;
        }

        return $response;
    }

    /**
     * Страница всех глав книги с id $id.
     */
    public function actionSections($id)
    {
        $book = Book::find()->select([
            'id',
            'title'
        ])->where(['id' => $id])->with('sections')->one();

        if ($book !== null) {
            return $this->render('sections', ['book' => $book]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Удаляет книгу (ajax).
     */
    public function actionDelete($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $response = ['status' => 0];

        if (Book::find()->where(['id' => $id])->exists()) {
            if (Book::remove($id)) {
                $response['status'] = 1;
                $response['messages'] = 'Книга была успешно удалена.';
            } else {
                $response['messages'] = 'Ошибка удаления книги.';
            }
        } else {
            throw new NotFoundHttpException;
        }

        return $response;
    }
}

frontend/controllers/BooksController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/30/2016
 * Time: 11:40 PM
 */

namespace frontend\controllers;


use avega\F;
use common\models\Book;
use common\models\Image;
use common\models\Section;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BooksController extends Controller
{
    /**
     * Страница с книгами.
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'books' => Book::find()
                ->orderBy('id DESC')
                ->asArray()
                ->all()
        ]);
    }

    /**
     * Страница всех глав книги.
     */
    public function actionView($id)
    {
        $book = Book::findOne($id);

        if ($book !== null) {
            return $this->render('view', [
                'sections' => Section::findAll(['bookId' => $id]),
                'book' => $book
            ]);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Страница просмотра изображений главы.
     */
    public function actionSection($id, $imageId = null)
    {
        $section = Section::findOne($id);

        if ($section !== null) {
            $book = Section::findBookBySectionId($id);

            return $this->render('images',
                [
                    'nextSection' => $section->getNextSection(),
                    'prevSection' => $section->getPrevSection(),
                    'book' => $book,
                    'section' => $section,
                    'images' => Image::find()
                        ->where(['sectionId' => $id])
                        ->select('id')
                        ->asArray()
                        ->all(),
                    'imageId' => $imageId
                ]);
        } else {
            throw new NotFoundHttpException;
        }
    }
}

backend/views/books/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 6:41 PM
 * @var $book
 * @var $this \yii\web\View
 */
\backend\assets\SummernoteAsset::register($this);
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-12 pull-left">
            <h3>Бла бла бла, название</h3>
        </div>
    </div>
</div>
<?php \avega\Insets::getAlert(['success', 'error']) ?>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Название</label>
                        <input type="text" id="title" class="form-control" value="<?= $book->title ?>">
                    </div>
                    <div class="form-group">
                        <input type="checkbox" id="cutFiles" value="<?= (int)$book->cutFiles ?>" <?= (bool)$book->cutFiles ? 'checked' : ''?>>
                        <label for="cutFiles">Разрезать каждый новый файл пополам</label>
                    </div>
                    <div class="row">
                        <div class="col-xs-9">
                            <div class="form-group">
                                <label>Обложка</label>
                                <input type="file" id="file" class="form-control" title="Обложка">
                            </div>
                        </div>
                        <div class="col-xs-3 pull-right">
                            <div class="form-group">
                                <button class="btn btn-info btn-md pull-right btn-upload-cover"
                                        style="margin-top: 24px;">Загрузить
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group progress-container" style="display: none;">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="0"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 0">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Описание</label>
                        <textarea id="description" class="form-control"><?= $book->description ?></textarea>
                    </div>
                    <div class="form-group">
                        <input type="hidden" id="cover" value="<?= $book->cover ?>">
                        <button class="btn btn-warning btn-md btn-update">Сохранить</button>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
    </div>
</div>
<script>
    var progressContainer = $('.progress-container');
    var progressBar = $('.progress-bar');

    // записываем в значение чекбокса состояние чекбокса
    $('#cutFiles').change(function () {
        $(this).val($(this).prop('checked') ? 1 : 0);
    });

    // клик по кнопке загрузки изображения
    $('.btn-upload-cover').click(function () {
        var file = document.getElementById('file').files[0];

        if (typeof file != typeof undefined) {

            var fd = new FormData();

            fd.append('cover', file);
            fd.append('_csrf', window._csrf);

            progressContainer.show();
            progressBar.addClass('active');

            // отсылаем на сервер изображение
            $.ajax({
                url: '<?= \yii\helpers\Url::to(['/books/upload-cover']) ?>',
                data: fd,
                type: 'POST',
                dataType: 'json',
                contentType: false,
                processData: false,
                xhr: function () {
                    var xhr = $.ajaxSettings.xhr();

                    if (xhr.upload) {
                        xhr.upload.onprogress = function (_xhr) {
                            var pos = parseInt(100 * _xhr.loaded / _xhr.total);

                            progressBar.css({'width': pos + '%'});

                            if (pos == 100) {
                                progressBar.removeClass('active');
                            }
                        }
                    }

                    return xhr;
                },
                success: function (response) {
                    var alertType = 'error';

                    if (response.status == 1) {
                        alertType = 'success';
                        $('#cover').val(response.fileName);
                    }

                    showAlert(alertType, response.messages)
                }
            });
        }
    });

    $(function () {
        $('#description').summernote();

        // после запроса ajax'a обновляем заголовок страницы сверху
        Form.prototype.afterUpdate = function (response, data) {
            if (response.status == 1) {
                $('.content-header h3').text(data.title);
            }
            this.afterSubmit(response, 'update');
        };

        (new Form('book', {
            'action': 'update',
            'url': '<?= \yii\helpers\Url::to(['/books/save/' . $book->id]) ?>',
            'fields': ['description', 'cover', 'title', 'cutFiles']
        }));
    });
</script>

backend/views/books/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 4:33 PM
 * @var $books array
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>Книги</h3>
        </div>
        <div class="col-md-6 pull-right">
            <a href="<?= \yii\helpers\Url::to(['/books/new']) ?>">
                <button class="btn btn-warning pull-right">Добавить книгу</button>
            </a>
        </div>
    </div>
</div>
<?php \avega\Insets::getAlert(['success', 'error']) ?>
<div class="content">
    <div class="books">
        <?php foreach ($books as $i => $book): ?>
            <!-- открыть строку если книга - первая, или первая в СТРОКЕ -->
            <?php $openRow = ($i == 0) || ($i % 4 === 0) ?>
            <!-- закрыть строку если книга - последняя или последняя в строке -->
            <?php $closeRow = $i === count($books) - 1 || ($i != 1 && ($i + 1) % 4 === 0) ?>
            <?php if ($openRow)  : ?>
                <div class="row">
            <?php endif ?>
            <?php $thumbnailUrl = \Yii::$app->params['coverUrl'] . \backend\models\BookForm::THUMBNAIL_WIDTH . 'x' . \backend\models\BookForm::THUMBNAIL_HEIGHT . '_' . $book['cover'] ?>
            <div class="col-md-3">
                <div class="book-item">
                    <a href="<?= \yii\helpers\Url::to(['/books/sections/' . $book['id']]) ?>">
                        <i class="fa fa-book view-book" aria-hidden="true"></i>
                    </a>
                    <i class="fa fa-times delete-book" title="Удалить" data-id="<?= $book['id'] ?>"></i>
                    <a href="<?= \yii\helpers\Url::to(['/books/edit/' . $book['id']]) ?>"><i
                            class="fa fa-pencil edit-book" title="Редактировать"></i></a>
                    <h5 class="book-title"><?= $book['title'] ?></h5>
                    <img src="<?= $thumbnailUrl ?>" alt="">
                </div>
            </div>
            <?php if ($closeRow)  : ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
</div>
<script>
    var body = $('body');

    var Book = {
        selectors: {
            /**
             * Кнопка удаления книги.
             */
            deleteBook: '.delete-book',
            /**
             * Контейнер со всеми книгами.
             */
            container: '.books'
        },

        handlers: {
            /**
             * Клик по кнопке удалить книгу.
             */
            deleteBook: function (event) {
                var id = $(this).data('id');

                event.data._this.deleteBook(id);
            }
        },
        /**
         * Функция спросить пользователя, хочет ли он удалить книгу.
         * @return {boolean}
         */
        beforeDeleteBook: function () {
            return confirm('Вы уверены что хотите удалить книгу? Вместе с ней будут удалены все главы и изображения.');
        },
        /**
         * Ajax запрос на удаление книги.
         * @param id
         * @return {boolean}
         */
        deleteBook: function (id) {
            var _this = this;

            if (!_this.beforeDeleteBook()) {
                return false;
            }

            $.ajax({
                url: '<?= \yii\helpers\Url::to(['/books/delete/']) ?>/' + id,
                type: 'POST',
                dataType: 'json',
                data: {_csrf: window._csrf},
                success: function (response) {
                    _this.afterDeleteBook(response, id);
                },
                error: function () {
                    alert('Ошибка удаления книги');
                }
            });
        },
        /**
         * Фк-ция выполниться после ajax запроса на удаление книги.
         * @param id
         * @param response
         */
        afterDeleteBook: function (response, id) {
            hideAlert();
            showAlert(response.status, response.messages);

            if (response.status == 1) {
                var row = $(this.selectors.deleteBook + '[data-id=' + id + ']').parent().parent().parent();

                if (row.find('.col-md-3').length == 1) {
                    row.remove();
                }else{
                    $(this.selectors.deleteBook + '[data-id=' + id + ']').parent().parent().remove();
                }

                this.reSortBooks();
            }
        },
        reSortBooks: function () {
            // клониурем массив со всеми книгами
            var books = $(this.selectors.container).find('.col-md-3').clone();
            $(this.selectors.container).html('');

            // здесь будет html код книг
            var html = '';

            $.each(books, function (index, book) {
                var openRow = index == 0 || index % 4 == 0;
                var closeRow = index == (books.length - 1) || (index != 1 && (index + 1) % 4 == 0);

                html += openRow ? '<div class="row">' : '';

                html += book.outerHTML;

                html += closeRow ? '</div>' : '';
            });

            // вставляем книги заново
            $(this.selectors.container).html(html);
        }
    };

    body.on('click', Book.selectors.deleteBook, {_this: Book}, Book.handlers.deleteBook);
</script>

backend/views/books/new.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 7/27/2016
 * Time: 10:10 PM
 */

\backend\assets\SummernoteAsset::register($this);
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-12 pull-left">
            <h3>Новая книга</h3>
        </div>
    </div>
</div>
<?php \avega\Insets::getAlert(['success', 'error']) ?>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Название</label>
                        <input type="text" id="title" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="checkbox" id="cutFiles">
                        <label for="cutFiles">Разрезать каждый новый файл пополам</label>
                    </div>
                    <div class="row">
                        <div class="col-xs-9">
                            <div class="form-group">
                                <label>Обложка</label>
                                <input type="file" id="file" class="form-control" title="Обложка">
                            </div>
                        </div>
                        <div class="col-xs-3 pull-right">
                            <div class="form-group">
                                <button class="btn btn-info btn-md pull-right btn-upload-cover" style="margin-top: 25px;">Загрузить</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group progress-container" style="display: none;">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Описание</label>
                        <textarea id="description" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="hidden" id="cover">
                        <button class="btn btn-warning btn-md btn-create">Создать</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var progressContainer = $('.progress-container');
    var progressBar = $('.progress-bar');

    function uploadCover(data) {
        $.ajax({
            url: '<?= \yii\helpers\Url::to(['/books/upload-cover']) ?>',
            data: data,
            type: 'POST',
            dataType: 'json',
            contentType: false,
            processData: false,
            xhr: function () {
                var xhr = $.ajaxSettings.xhr();

                if (xhr.upload) {
                    xhr.upload.onprogress = function (_xhr) {
                        var pos = parseInt(100 * _xhr.loaded / _xhr.total);

                        progressBar.css({'width': pos + '%'});

                        if (pos == 100) {
                            progressBar.removeClass('active');
                        }
                    }
                }

                return xhr;
            },
            success: function (response) {
                var alertType = 'error';

                if (response.status == 1) {
                    alertType = 'success';
                    $('#cover').val(response.fileName);
                }

                showAlert(alertType, response.messages)
            }
        });
    }

    $('.btn-upload-cover').click(function () {
        var file = document.getElementById('file').files[0];

        if (typeof file != typeof undefined) {

            var fd = new FormData();

            fd.append('cover', file);
            fd.append('_csrf', window._csrf);

            progressContainer.show();
            progressBar.addClass('active');

            uploadCover(fd);
        }
    });

    $(function () {
        $('#description').summernote();

        (new Form('book', {
            'action': 'create',
            'url': '<?= \yii\helpers\Url::to(['/books/save/']) ?>',
            'fields': ['description', 'cover', 'title', 'cutFiles']
        }));
    });
</script>